### ISSUE TITLE
Extract Kilinc model

### ISSUE THREAD

**Issue by brainylyasha** [brainylyasha/liquid-solver#1]
Extract Kilinc oxidation model as an independent choice from current implementation of Toplis olivine-melt model.
NB. When computing the temperature original manipulated (without division) oxid fractions should be used.

**Comment by serbunka** [comment]
AHAHHAH

**Comment by serbunka** [comment]
hello

**Comment by serbunka** [comment]
answer!!!!!!!!

**Comment by brainylyasha** [comment]
STOP IT!!1!

**Comment by serbunka** [comment]
[Kilinc83.xlsx](https://github.com/brainylyasha/liquid-solver/files/1567846/Kilinc83.xlsx)

**Comment by brainylyasha** [comment]
Works only with experimental temperature; scenario with temperature computation needs more understanding and some formulas' correction
