### ISSUE TITLE
Sack80

### ISSUE THREAD

**Issue by serbunka** [brainylyasha/liquid-solver#4]
Модель расчета отношений желез. Там одна формулка буквально)
[Sack80.xlsx](https://github.com/brainylyasha/liquid-solver/files/1630940/Sack80.xlsx)

**Comment by brainylyasha** [comment]
Кам огна фовмувка буквайна

**Comment by serbunka** [comment]
ТАК ЭТО ЕЩЕ ЧТО

**Comment by serbunka** [comment]
ГДЕ МОЯ МОДЕЕЕЕЕЕЛЬЬЬЬЬЬЬЬЬ

**Comment by brainylyasha** [comment]
ГЕ МАЯ МАГЕЙ

**Comment by serbunka** [comment]
гей маяма гей
