### ISSUE TITLE
база данных

### ISSUE THREAD

**Issue by serbunka** [brainylyasha/liquid-solver#7]
тэкс значит. есть файлы condit-3, oliv-3, liq-3, bibl-3. Я хочу собрать данные для экспериментов с оливином. Для этого в файле condit-3 я нахожу строки, в которых Phase-1 имеет любое из значений "OL", "OL1", "OL2", "OL?" или "LQ1" и Phase-2 тоже любое из этих значений. При этом в Phase-3 должно быть пусто. После этого для каждой найденной строки я в соответствующем файле (oliv-3 или liq-3) ищу соответствующую строку. Ищу по двум номерам, в файле condit-3 они называются Reference и Run. найденную строку из файлов oliv-3 и/или liq-3 вставляю в пустые столбцы в файле condit-3. Дальше еще в файле bibl-3 нахожу соответствующую строку по номеру и тоже пихаю в condit-3. Выдаю condit-3. Пример того, что должно быть на выходе в файле output. 
А, да, если он вдруг не может найти нужные строки в файлах, то пишет тогда в аутпут для них not found

**Comment by brainylyasha** [comment]
Done, выдала результат на руки
